
services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./core:/core
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"


  database:
    image: postgres:14.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    volumes:
      - pgdata:/var/lib/postgresql/data



#  redis:
#    image: redis:7.0.5-alpine
#    hostname: redis
#
#  worker:
#    build:
#      context: .
#    hostname: worker
#    entrypoint: celery
#    command: -A celery_app.app worker --loglevel=info
#    volumes:
#      - ./core:/core
#    links:
#      - redis
#    depends_on:
#      - database
#      - redis
#    environment:
#      - DB_HOST=database
#      - DB_NAME=dbname
#      - DB_USER=dbuser
#      - DB_PASS=pass
#
#  flower:
#    build:
#      context: .
#    hostname: flower
#    entrypoint: celery
#    command: -A celery_app.app flower
#    volumes:
#      - ./core:/core
#    links:
#      - redis
#    depends_on:
#      - redis
#    ports:
#      - "5555:5555"

volumes:
  pgdata:
